### PR TITLE
2.4 Implemented PXB-2260 (allow test suite to run multiple tests)

### PR DESCRIPTION
**Pull request by altmannmarcelo**
https://jira.percona.com/browse/PXB-2260

Adjusted argument handling to allow multiple test to be passed via -t parameter

### CODE REVIEW

**Comment by altmannmarcelo** [comment]
https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium/97/ 

We should see two worker threads like bellow:

```
+ ./run.sh -c innodb57 -f -t t/argument_handling.sh -t t/broken_pipe.sh
Warning: -c does not have any effect and is only recognized for compatibility
Using /mnt/jenkins/workspace/percona-xtrabackup-2.4-param-medium/BUILD_TYPE/release/Host/min-centos-7-x64/xtrabackuptarget/innodb57/storage/innobase/xtrabackup/test/var as test root
Detecting server version...
Running against MySQL 5.7.21-log (InnoDB 5.7.21)
Using 'xtrabackup' as xtrabackup binary
Using 4 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
argument_handling                        w1	[passed]    1
broken_pipe                              w2	[passed]    13
==============================================================================
Spent 14 of 28 seconds executing testcases
```

**Comment by satya-bodapati** [comment]
> https://pxb.cd.percona.com/job/percona-xtrabackup-2.4-param-medium/97/
> 
> We should see two worker threads like bellow:
> 
> ```
> + ./run.sh -c innodb57 -f -t t/argument_handling.sh -t t/broken_pipe.sh
> Warning: -c does not have any effect and is only recognized for compatibility
> Using /mnt/jenkins/workspace/percona-xtrabackup-2.4-param-medium/BUILD_TYPE/release/Host/min-centos-7-x64/xtrabackuptarget/innodb57/storage/innobase/xtrabackup/test/var as test root
> Detecting server version...
> Running against MySQL 5.7.21-log (InnoDB 5.7.21)
> Using 'xtrabackup' as xtrabackup binary
> Using 4 parallel workers
> 
> ==============================================================================
> TEST                                   WORKER    RESULT     TIME(s) or COMMENT
> ------------------------------------------------------------------------------
> argument_handling                        w1	[passed]    1
> broken_pipe                              w2	[passed]    13
> ==============================================================================
> Spent 14 of 28 seconds executing testcases
> ```

Looks good. Just want to know if the repetivite "-t" can be avoided easily or not?

**Comment by rahulmalik87** [comment]
mention the usage in ./run.sh -h

**Comment by altmannmarcelo** [comment]
@satya-bodapati not with the way arguments are parsed at the moment. At least with the best of my knowledge
@rahulmalik87 fixed

**Review by satya-bodapati — APPROVED** [review]

**Review by rahulmalik87 — APPROVED** [review]
LGTM

**Pull request merged**
