### PR TITLE
PXB-1637: Readding O_DIRECT messages

### PR DESCRIPTION
**Pull request by dutow**

### CODE REVIEW

**Review by gl-sergei — APPROVED** [review]

**Comment by gl-sergei** [comment]
On second thought, why not just print out `innodb_flush_method_names[innodb_flush_method]` ?

**Comment by dutow** [comment]
It's based on the 2.4 implementation, which only printed out if some kind of O_DIRECT was used - if you think its better, I could change it to always print the correct name.

**Comment by gl-sergei** [comment]
I don't have strong opinion on that. Lets keep previous behaviour. This PR is good to merge

**Comment by dutow** [comment]
https://pxb.cd.percona.com/view/PXB%208.0/job/percona-xtrabackup-8.0-param-medium/9/

**Pull request merged**
