### PR TITLE
Pxb 8.0 2723 xbcloud Azure password leaked in process status

### PR DESCRIPTION
**Pull request by rahulmalik87**
https://jira.percona.com/browse/PXB-2723

    Hide xbcloud password from the ps output
    Backported pxb-2112 test case into 2.4
    Fixed check_for_passwords.sh test case

### CODE REVIEW

**Review by satya-bodapati — APPROVED** [review]
Please test on jenkins before push

**Comment by rahulmalik87** [comment]
> Please test on jenkins before push

Some issue with single platform jobs which Luis is trying to fix. will run the jobs once it is fixed.

**Review by altmannmarcelo — APPROVED** [review]

**Comment by rahulmalik87** [comment]
@satya-bodapati , 

result on lab machine 3 failure  are max open files on lab machine.  I am going to merge. 

SUMMARY: 333 run, 275 successful, 55 skipped, 3 failed

Skipped tests:  binlog.bug1250375 keyring.innodb_encryption_mix_plugins keyring.innodb_keyring_kmip_component keyring.innodb_keyring_vault_auto_v1 keyring.innodb_keyring_vault_auto_v2 keyring.innodb_keyring_vault_v1 keyring.innodb_keyring_vault_v2 keyring.keyring_encryption keyring.pxb-1793 keyring.shared_tablespace_encryption keyring.xb_log_archiving_encrypt rocksdb.compress rocksdb.cross_engine_trx rocksdb.datadir rocksdb.ddl rocksdb.local_max_age rocksdb.local rocksdb.log_status rocksdb.stream_compress_encrypt rocksdb.stream_compress rocksdb.stream rocksdb.wal_dir_abs_archive rocksdb.wal_dir_abs rocksdb.wal_dir_rel rocksdb.compress_encrypt main.backup_locks main.bug1192834-purge main.bug1192834-rollback main.bug1227240 main.bug1347698 main.bug1394493 main.bug1415191 main.bug1418584 main.bug1475487 main.bug1533722 main.bug382742 main.bug759225 main.bug766305 main.bug976945 main.bug983720_galerainfo main.bug983720_lrudump main.distribution_message main.ib_doublewrite main.ib_lru_dump_basic main.ib_lru_dump_rsync main.ib_lru_dump_stream main.ib_part_tf_myisam main.innodb_fast_checksum main.innodb_log_checksum_algorithm main.pxb-1824 main.pxb-1914 main.xb_apply_archived_logs main.xb_galera_info main.xb_galera_sst main.xb_log_archiving

Failed tests:  main.PXB-1548_basic main.PXB-1548_rsync_basic main.pxb-1870

**Comment by satya-bodapati** [comment]
go ahead @rahulmalik87

**Pull request merged**
