### PR TITLE
PXB-3336 Fix FTS index pattern typo

### PR DESCRIPTION
**Pull request by zhaoxinyu**
fix: https://perconadev.atlassian.net/browse/PXB-3336

### CODE REVIEW

**Comment by zhaoxinyu** [comment]
@satya-bodapati

**Review by satya-bodapati — APPROVED** [review]
Good catch!

**Comment by zhaoxinyu** [comment]
Is this pull request ready to be merged? @satya-bodapati

**Comment by satya-bodapati** [comment]
@zhaoxinyu Yes, it will be released as part of the PXB-8.0.35-32 release. We will merge it soon.

**Review by satya-bodapati — APPROVED** [review]

**Pull request merged**
