### PR TITLE
Gca trunk

### PR DESCRIPTION
**Pull request by altmannmarcelo**
Advanced GCA point of 8.0

### CODE REVIEW

**Comment by altmannmarcelo** [comment]
## Testing

```
XBCLOUD_CREDENTIALS='--storage=s3 --s3-endpoint='http://172.18.0.2:9000' --s3-access-key=myuser --s3-secret-key=someStrongPWD --s3-bucket=newbucket' KMIP_CLIENT_CA="/tmp/certs/client_certificate_jane_doe.pem" KMIP_CLIENT_KEY="/tmp/certs/client_key_jane_doe.pem" KMIP_SERVER_CA="/tmp/certs/root_certificate.pem" VAULT_URL=https://127.0.0.1:8200 VAULT_CACERT=${HOME}/vault.crt VAULT_CA=${HOME}/vault.crt VAULT_TOKEN=hvs.OiCBiHrOSsqC3U6Qbn39LZjs ./run.sh -r /dev/shm/ -d /work/ps/ins/8.0/ -f 
Using /dev/shm//var as test root
Detecting server version...
Running against Percona Server 8.1.0-1-debug (XtraDB 8.1.0-1)
Using 'xtrabackup' as xtrabackup binary
Autodetected number of cores: 32
Limiting to 16 to avoid excessive resource consumption
Using 16 parallel workers
Running suite(s): pagetracking binlog gr keyring compression rocksdb main xbcloud

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
binlog.binlog_108                        w8	[passed]    34
binlog.binlog_105                        w5	[passed]    36
binlog.binlog_111                        w12	[passed]    36
binlog.binlog_201                        w15	[passed]    35
binlog.binlog_101                        w1	[passed]    37
binlog.binlog_102                        w2	[passed]    37
binlog.binlog_103                        w3	[passed]    37
binlog.binlog_104                        w4	[passed]    37
binlog.binlog_106                        w6	[passed]    37
binlog.binlog_107                        w7	[passed]    37
binlog.binlog_109                        w9	[passed]    37
binlog.binlog_10                         w10	[passed]    37
binlog.binlog_110                        w11	[passed]    37
binlog.binlog_11                         w13	[passed]    37
binlog.binlog_1                          w14	[passed]    36
binlog.bug1250375                        w14	[skipped]   Requires Galera support
binlog.binlog_202                        w16	[passed]    36
binlog.bug1168513                        w11	[passed]    23
binlog.bug1192347                        w13	[passed]    24
binlog.binlog_203                        w8	[passed]    33
binlog.bug1391041                        w14	[passed]    31
binlog.binlog_301                        w12	[passed]    34
binlog.bug1523687                        w16	[passed]    33
binlog.binlog_2                          w5	[passed]    36
binlog.binlog_302                        w15	[passed]    36
binlog.binlog_3                          w1	[passed]    36
binlog.binlog_4                          w2	[passed]    36
binlog.binlog_5                          w3	[passed]    36
binlog.binlog_6                          w4	[passed]    36
binlog.binlog_7                          w6	[passed]    36
binlog.binlog_9                          w9	[passed]    36
binlog.binlog_8                          w7	[passed]    37
binlog.binlog_info                       w10	[passed]    45
binlog.gtid                              w8	[passed]    22
binlog.xb_perm_basic                     w12	[passed]    29
binlog.xb_perm_stream                    w16	[passed]    29
pagetracking.encryption_after_checkpoint w5	[passed]    35
binlog.bug977101                         w13	[passed]    46
binlog.bug907147                         w11	[passed]    48
keyring.bug1590351                       w13	[passed]    23
pagetracking.xb_incremental_compressed_pagetracking_16kb w1	[passed]    67
pagetracking.xb_incremental_disable_enable_pagetracking w9	[passed]    70
pagetracking.xb_incremental_disable_pagetracking w7	[passed]    73
keyring.basic_encrytion                  w5	[passed]    44
pagetracking.xb_incremental_compressed_pagetracking_8kb w6	[passed]    89
pagetracking.xb_incremental_pagetracking_lsn w10	[passed]    88
keyring.innodb_keyring_kms_component     w10	[skipped]   Keyring kms requires KMS variables configured
keyring.innodb_keyring_plugin_to_component w10	[skipped]   Disabled until PXB-2969 is fixed
gr.gr_basic                              w12	[passed]    75
gr.slave_info                            w16	[passed]    76
pagetracking.xb_incremental_pagetracking w8	[passed]    87
keyring.bug1737525                       w11	[passed]    68
keyring.innodb_encryption_mix_plugins    w1	[passed]    37
keyring.innodb_encryption_export         w13	[passed]    56
keyring.keyring_encryption               w13	[skipped]   Requires server version lower than 8.0.30
binlog.ib_slave_info                     w14	[passed]    124
keyring.innodb_keyring_proxy_plugin      w10	[passed]    25
pagetracking.xb_incremental_compressed_pagetracking_1kb w2	[passed]    135
keyring.pxb-1793                         w10	[passed]    24
keyring.pxb-1705                         w14	[passed]    35
pagetracking.xb_incremental_compressed_pagetracking_2kb w3	[passed]    162
keyring.pxb-1903                         w10	[passed]    27
pagetracking.xb_incremental_compressed_pagetracking_4kb w4	[passed]    181
keyring.pxb-1937                         w3	[passed]    28
keyring.pxb-1879                         w2	[passed]    61
keyring.pxb-1954                         w10	[passed]    27
keyring.innodb_redo_log_encrypt          w1	[passed]    99
keyring.pxb-1936                         w14	[passed]    51
keyring.pxb-2429                         w4	[passed]    36
keyring.shared_tablespace_encryption     w1	[passed]    39
keyring.reencrypt                        w2	[passed]    49
keyring.system_tablespace_encryption     w14	[passed]    42
keyring.innodb_keyring_vault_v1          w8	[passed]    147
xbcloud.ec2_instance_profile             w14	[skipped]   This test requires EC2 Instance Profile set
keyring.innodb_keyring_vault_auto_v1     w12	[passed]    151
xbcloud.storage_class                    w12	[skipped]   Storage Class is not supported on MinIO servers
keyring.rollback                         w10	[passed]    53
keyring.innodb_keyring_vault_auto_v2     w16	[passed]    151
keyring.keyring_pxb_2275                 w13	[passed]    144
keyring.innodb_keyring_vault_v2          w11	[passed]    156
compression.bug1418438                   w10	[passed]    24
compression.bug1242309                   w12	[passed]    27
pagetracking.validate_tracking_start_lsn w15	[passed]    291
keyring.xb_log_archiving_encrypt         w4	[passed]    76
keyring.innodb_keyring_file_plugin       w5	[passed]    217
xbcloud.backup_incomplete                w1	[passed]    53
xbcloud.redact_password                  w14	[passed]    55
compression.bug977652                    w16	[passed]    52
compression.bug983695                    w13	[passed]    55
compression.ib_compress_basic            w11	[passed]    59
keyring.innodb_keyring_file_both         w9	[passed]    255
xbcloud.basic_operations                 w2	[passed]    82
compression.page_compression_lz4_multi_thread w10	[passed]    52
compression.page_compression_lz4         w12	[passed]    52
xbcloud.fifo                             w8	[passed]    89
rocksdb.compress_encrypt                 w8	[skipped]   Requires RocksDB
rocksdb.compress                         w8	[skipped]   Requires RocksDB
rocksdb.cross_engine_trx                 w8	[skipped]   Requires RocksDB
rocksdb.datadir                          w8	[skipped]   Requires RocksDB
rocksdb.ddl                              w8	[skipped]   Requires RocksDB
rocksdb.local_max_age                    w8	[skipped]   Requires RocksDB
rocksdb.local                            w8	[skipped]   Requires RocksDB
rocksdb.log_status                       w8	[skipped]   Requires RocksDB
rocksdb.stream_compress_encrypt          w8	[skipped]   Requires RocksDB
rocksdb.stream_compress                  w8	[skipped]   Requires RocksDB
rocksdb.stream                           w8	[skipped]   Requires RocksDB
rocksdb.wal_dir_abs_archive              w8	[skipped]   Requires RocksDB
rocksdb.wal_dir_abs                      w8	[skipped]   Requires RocksDB
rocksdb.wal_dir_rel                      w8	[skipped]   Requires RocksDB
compression.pxb-1901                     w14	[passed]    36
compression.page_compression_no_compress w15	[passed]    61
main.argument_handling                   w15	[passed]    1
compression.page_compression_zstd_multi_thread w4	[passed]    61
compression.page_compression_zstd        w5	[passed]    63
compression.pxb-1552                     w1	[passed]    65
keyring.innodb_keyring_file_component    w7	[passed]    287
compression.xb_compress_lz4              w16	[passed]    57
keyring.redo_log_archive                 w3	[passed]    176
compression.xb_compress                  w13	[passed]    56
main.broken_pipe                         w4	[passed]    22
compression.xb_parallel_compress         w9	[passed]    58
compression.xb_stream_compress_lz4       w2	[passed]    60
keyring.innodb_keyring_kmip_component    w6	[passed]    299
compression.xb_stream_compress           w10	[passed]    60
compression.xbstream_parallel_decrypt_decompress_lz4 w12	[passed]    60
main.bug1022562                          w1	[passed]    38
main.bug1038127                          w3	[passed]    33
main.bug1042887                          w13	[passed]    31
main.bug1028949                          w7	[passed]    39
main.bug1049291                          w4	[passed]    27
main.all_files                           w8	[passed]    68
main.backup_locks                        w15	[passed]    56
main.bug1085099                          w2	[passed]    23
main.bug1037379                          w16	[passed]    49
main.bug1192834-purge                    w16	[skipped]   Enable when bug #1192834 is fixed in 2.4
main.bug1192834-rollback                 w16	[skipped]   Enable when bug #1192834 is fixed in 2.4
main.bug1125993                          w10	[passed]    23
main.bug1112224                          w6	[passed]    28
main.bug1227240                          w6	[skipped]   Requires server version lower than 5.7.0
main.bug1135431                          w1	[passed]    22
main.bug1247586                          w1	[passed]    1
main.bug1062684                          w9	[passed]    38
main.bug1164945                          w3	[passed]    27
main.bug1002688                          w5	[passed]    69
main.bug1273207                          w5	[passed]    0
main.bug1180922                          w7	[passed]    29
main.bug1130627                          w12	[passed]    37
main.bug1177201                          w13	[passed]    30
main.bug1183793                          w8	[passed]    22
main.bug1190335                          w15	[passed]    23
main.bug1347698                          w15	[skipped]   Requires server version lower than 5.6.0
main.bug1190716                          w2	[passed]    23
main.bug1222062                          w10	[passed]    23
compression.xb_compress_zstd             w11	[passed]    117
main.bug1206363                          w16	[passed]    24
main.bug1376874                          w11	[passed]    1
main.bug1182726                          w4	[passed]    43
main.bug1394493                          w4	[skipped]   Requires TokuDB
main.bug1277403                          w5	[skipped]   Requires server without backup locks support
main.bug1367377                          w2	[passed]    21
main.bug1291299                          w7	[failed]    27
main.bug1415191                          w7	[skipped]   Requires server version lower than 5.7.0
main.bug1418584                          w7	[skipped]   Requires Galera support
main.bug1254227                          w3	[passed]    33
main.bug1388122                          w11	[passed]    23
main.bug1475487                          w11	[skipped]   Requires server version lower than 8.0.1
main.bug1239670                          w6	[passed]    43
main.bug1334062                          w12	[passed]    30
main.bug1410339                          w5	[passed]    26
main.bug1511451                          w5	[passed]    1
main.bug1343722                          w8	[passed]    45
main.bug1399471                          w4	[passed]    30
main.alter_instance_redo                 w14	[passed]    137
main.bug1508448                          w6	[passed]    23
main.bug1454815                          w7	[passed]    26
main.bug1495367                          w11	[passed]    24
main.bug1533722                          w11	[skipped]   Requires PS 5.5.23 or higher, but less than 5.6
main.bug1509812                          w12	[passed]    26
main.bug1340717                          w13	[passed]    62
main.bug1382347                          w16	[passed]    59
main.bug1511701                          w5	[passed]    23
main.bug1461735                          w3	[passed]    39
main.bug1513520                          w4	[passed]    23
main.bug1248331                          w9	[passed]    78
main.bug1363234                          w15	[passed]    70
main.bug1533542                          w7	[passed]    21
main.bug1512616                          w8	[passed]    30
main.bug1527081                          w14	[passed]    31
main.bug1532101                          w6	[passed]    31
main.bug1414221                          w2	[passed]    60
main.bug382742                           w2	[skipped]   Requires server version lower than 5.7.0
main.bug1566228                          w13	[passed]    25
main.bug1600656                          w16	[passed]    23
main.bug1535312                          w11	[passed]    36
main.bug528752                           w11	[passed]    1
main.bug1623210                          w5	[passed]    27
main.bug664128                           w5	[passed]    1
main.bug1706582                          w8	[passed]    21
main.bug1652044                          w9	[passed]    25
main.bug1630841                          w3	[passed]    32
main.bug1691093                          w7	[passed]    31
main.bug369913                           w6	[passed]    23
main.bug759225                           w6	[skipped]   Requires server version lower than 5.7.0
main.bug1669592                          w15	[passed]    36
main.bug483827                           w2	[passed]    26
main.bug1642826                          w4	[passed]    42
main.bug514068                           w16	[passed]    26
main.bug664986                           w5	[passed]    20
main.bug729843                           w9	[passed]    20
main.bug733651                           w3	[passed]    23
main.bug723097                           w8	[passed]    29
main.bug489290                           w13	[passed]    38
main.bug766305                           w2	[passed]    21
main.bug1372679                          w10	[passed]    129
main.bug884737                           w3	[passed]    23
main.bug976945                           w3	[skipped]   Requires server version lower than 5.7.0
main.bug856400                           w5	[passed]    33
main.bug983720_galerainfo                w5	[skipped]   Requires Galera support
main.bug983720_lrudump                   w5	[skipped]   Requires Percona Server <= 5.5
main.bug606981                           w11	[passed]    58
main.bug766607                           w4	[passed]    42
main.bug1717158                          w14	[passed]    75
main.bug950334                           w10	[passed]    25
main.bug766033                           w15	[passed]    51
main.bug740489                           w7	[passed]    57
main.bug932623                           w13	[passed]    37
main.bug870119                           w9	[passed]    50
main.bug983685                           w3	[passed]    23
main.bug1248065                          w1	[passed]    179
main.bug803636                           w16	[passed]    58
main.bug989397                           w5	[passed]    24
main.distribution_message                w5	[skipped]   Requires XB_DISTRIBUTION to be set
main.bug759701                           w6	[passed]    67
main.bug996493                           w11	[passed]    25
main.check_for_passwords_debug           w4	[passed]    24
main.bug1551634                          w12	[passed]    126
main.bug930062                           w8	[passed]    59
main.bug943750                           w2	[passed]    59
main.ddl                                 w15	[passed]    36
main.create_tablespace                   w10	[passed]    37
main.ib_buffer_pool_rsync                w12	[passed]    23
main.ib_doublewrite                      w12	[skipped]   Requires Percona Server <= 5.5
main.check_for_passwords                 w14	[passed]    53
main.ib_buffer_pool_dump_incremental     w4	[passed]    33
main.ib_buffer_pool                      w8	[passed]    28
main.ib_lru_dump_basic                   w8	[skipped]   Requires Percona Server <= 5.5
main.ib_lru_dump_rsync                   w8	[skipped]   Requires Percona Server <= 5.5
main.ib_lru_dump_stream                  w8	[skipped]   Requires Percona Server <= 5.5
main.dictionary_sdi                      w9	[passed]    47
main.dictionary_part2                    w13	[passed]    55
main.ib_csm_csv                          w2	[passed]    31
main.history_on_server                   w11	[passed]    50
main.ib_databases_file                   w15	[passed]    34
main.ib_empty_dir                        w12	[passed]    25
main.handle_errors                       w6	[passed]    59
main.ib_databases                        w10	[passed]    36
main.dictionary_sub_part2                w16	[passed]    61
main.ib_part_databases                   w8	[passed]    30
main.innodb_fast_checksum                w8	[skipped]   Requires server version lower than 5.6.0
main.innodb_log_checksum_algorithm       w8	[skipped]   Requires server version lower than 5.7.0
main.ib_part_include                     w9	[passed]    31
main.ib_part_include_stream              w13	[passed]    30
main.ib_part_tf_myisam                   w15	[skipped]   Requires server version lower than 8.0.0
main.ib_part_tf_innodb                   w2	[passed]    29
main.ib_part_tf_innodb_stream            w11	[passed]    29
main.dictionary_part1                    w7	[passed]    103
main.kill_long_selects                   w15	[skipped]   Requires a server without backup locks support
main.dictionary_sub_part1                w1	[passed]    107
main.ib_incremental_full_scan_lsn        w14	[passed]    78
main.ib_incremental_full_scan            w4	[passed]    78
main.ib_rsync_nolock                     w12	[passed]    58
main.instant_columns                     w13	[passed]    41
main.dictionary                          w3	[passed]    119
main.ib_rsync                            w6	[passed]    57
main.ib_specialchar                      w10	[passed]    57
main.innodb_data_home_dir                w16	[passed]    58
main.pxb-1493                            w7	[passed]    28
main.pxb-1536                            w15	[passed]    37
main.pxb-1569                            w13	[passed]    24
main.pxb-1700                            w10	[passed]    24
main.pxb-1807                            w13	[passed]    1
main.parallel_copyback                   w11	[passed]    63
main.mdl_locks                           w2	[passed]    69
main.pxb-1714                            w7	[passed]    32
main.PXB-1548_basic                      w1	[passed]    49
main.pxb-1679                            w3	[passed]    38
main.pxb170                              w16	[passed]    38
main.PXB-1548_dump_pct                   w14	[passed]    48
main.PXB-1548_rsync_basic                w4	[passed]    49
main.pxb-2357                            w4	[skipped]   This test is not testing what it is intended to. Check PXB-3110
main.pxb-1694                            w6	[passed]    48
main.pxb-2371                            w4	[passed]    0
main.pxb-2422                            w6	[passed]    0
main.PXB-1548_rsync_dump_pct             w12	[passed]    49
main.PXB-2854_xbstream_memory_corruption w4	[passed]    1
main.pxb-1902                            w2	[passed]    23
main.pxb-1784                            w15	[passed]    37
main.pxb-1862                            w13	[passed]    34
main.pxb-1951                            w3	[passed]    27
main.pxb-1913                            w7	[passed]    32
main.pxb-1914                            w1	[passed]    30
main.pxb-1953                            w16	[passed]    31
main.innodb_log_checksums                w8	[passed]    120
main.PXB-197                             w14	[passed]    28
main.unittests                           w14	[passed]    0
main.pxb-1824                            w10	[passed]    54
main.simulate_lower_version              w15	[passed]    24
main.server_version                      w2	[passed]    29
main.xb_apply_archived_logs              w2	[skipped]   Enable when archived logs functionality restored
main.tablespace_corruption               w7	[passed]    19
main.throttle                            w1	[passed]    28
main.xbcrypt                             w1	[passed]    1
main.stop_before_copy_log_hdr            w3	[passed]    34
main.redo_log_consumer                   w12	[passed]    51
main.skip_orphan_table                   w13	[passed]    41
main.validate_copy_back                  w10	[passed]    23
main.user_management                     w14	[passed]    33
main.version_check                       w15	[failed]    29
main.undo_truncation                     w8	[passed]    39
main.xb_galera_info                      w8	[skipped]   Requires Galera support
main.xb_galera_sst                       w8	[skipped]   Requires Galera support
main.read_buffer_size                    w6	[passed]    68
main.estimate_memory                     w5	[passed]    236
main.xb_defaults_file                    w12	[passed]    23
main.pxb-1870                            w11	[passed]    99
main.xb_export_check_cfg                 w14	[passed]    24
main.innodb_page_size                    w9	[passed]    178
main.xb_decompress_file_validations      w3	[passed]    36
main.remote_tablespaces                  w4	[passed]    86
main.xb_basic                            w2	[passed]    59
main.xb_databases_options                w1	[passed]    56
main.xb_encrypt                          w10	[passed]    59
main.xb_duplicate_sdi                    w13	[passed]    68
main.xb_export                           w15	[passed]    68
main.xb_print_param                      w15	[passed]    1
main.xb_incremental_compressed_full_scan_16kb w8	[passed]    66
main.xb_parallel_encrypt                 w4	[passed]    60
main.xb_parallel_compress_encrypt        w3	[passed]    61
main.xb_remove_original                  w15	[passed]    26
main.xb_compress_encrypt                 w7	[passed]    120
main.xb_log_overwrap                     w9	[passed]    73
main.xb_part_range                       w10	[passed]    47
main.xb_log_archiving                    w14	[passed]    79
main.xb_pause_after_log_status           w13	[passed]    42
main.xb_version                          w13	[passed]    0
main.xb_parallel                         w1	[passed]    62
main.xb_incremental_compressed_full_scan_8kb w11	[passed]    92
main.xb_stream_compress_encrypt          w8	[passed]    67
main.xb_stream_encrypt                   w4	[passed]    60
main.xb_incremental_compressed_full_scan_4kb w12	[passed]    135
main.xbstream_parallel_decrypt_decompress w15	[passed]    62
main.xbstream_parallel_decrypt           w7	[passed]    60
main.xb_stream_parallel_encrypt          w9	[passed]    63
main.xb_stream_parallel                  w10	[passed]    62
main.xb_stream_xbstream                  w14	[passed]    62
main.xb_parallel_incremental             w2	[passed]    135
main.xb_incremental_compressed_full_scan_2kb w5	[passed]    164
main.xbstream_fifo                       w3	[passed]    94
main.xb_incremental_compressed_full_scan_1kb w6	[passed]    180
main.undo_tablespaces                    w16	[passed]    278
==============================================================================
Spent 16893 of 1158 seconds executing testcases

SUMMARY: 360 run, 310 successful, 48 skipped, 2 failed

Skipped tests:  binlog.bug1250375 keyring.innodb_keyring_kms_component keyring.innodb_keyring_plugin_to_component keyring.keyring_encryption xbcloud.ec2_instance_profile xbcloud.storage_class rocksdb.compress_encrypt rocksdb.compress rocksdb.cross_engine_trx rocksdb.datadir rocksdb.ddl rocksdb.local_max_age rocksdb.local rocksdb.log_status rocksdb.stream_compress_encrypt rocksdb.stream_compress rocksdb.stream rocksdb.wal_dir_abs_archive rocksdb.wal_dir_abs rocksdb.wal_dir_rel main.bug1192834-purge main.bug1192834-rollback main.bug1227240 main.bug1347698 main.bug1394493 main.bug1277403 main.bug1415191 main.bug1418584 main.bug1475487 main.bug1533722 main.bug382742 main.bug759225 main.bug976945 main.bug983720_galerainfo main.bug983720_lrudump main.distribution_message main.ib_doublewrite main.ib_lru_dump_basic main.ib_lru_dump_rsync main.ib_lru_dump_stream main.innodb_fast_checksum main.innodb_log_checksum_algorithm main.ib_part_tf_myisam main.kill_long_selects main.pxb-2357 main.xb_apply_archived_logs main.xb_galera_info main.xb_galera_sst

Failed tests:  main.bug1291299 main.version_check

See results/ for detailed output
```

**Review by satya-bodapati — COMMENTED** [review]
I believe you just merged 8.0 to trunk. And this happened because we didn't merge every new 8.0 commit to 8.1?

Will we need to repeat the same exercise again in future? I think that if every commit from now follows GCA, we will not need the bulk GCA merge PRs? right @altmannmarcelo

**Comment by altmannmarcelo** [comment]
@satya-bodapati correct, we will now have to create the 8.0 branches with the last GCA point, and do the trunk PR merging the corresponding GCA branch with the fixes.
Then eventually, we will need to advance GCA to bring the commits belonging to 8.0 only into trunk.
Good old times :D

**Comment by satya-bodapati** [comment]
> @satya-bodapati correct, we will now have to create the 8.0 branches with the last GCA point, and do the trunk PR merging the corresponding GCA branch with the fixes. Then eventually, we will need to advance GCA to bring the commits belonging to 8.0 only into trunk. Good old times :D

Yeah, good old painful times :laughing: 

Can we exclude some folders from GCA points? I remember docs and build team has two folders, that are different across versions and they do not like GCA.

Luckily docs moved out of PXB source tree but build folders are in PXB tree. It would be great if we can add them to ignore or exemption folders.

I remember Rahul used to do GCA merges at frequent intervals. He did NULL Merge them and keep them in sync. Better if we can avoid this with the exemption/ignore list.

**Comment by altmannmarcelo** [comment]
> Can we exclude some folders from GCA points?
Hmm, don't know if that is possible. But since docs are no longer part of the repo, what would be the usage of it? Packaging commits?

This is the first release of trunk. We are kind of in an in-transit state until we have the flow all figured out. In this particular case, we had two sets of commits that did not followed GCA. The vault removal of unused code and mine work on bootstrap and test cases. Going forward we should enforce GCA on all of those. Perhaps even have a github action to validate it.

**Comment by satya-bodapati** [comment]
> > Can we exclude some folders from GCA points?
> > Hmm, don't know if that is possible. But since docs are no longer part of the repo, what would be the usage of it? Packaging commits?
> 
> This is the first release of trunk. We are kind of in an in-transit state until we have the flow all figured out. In this particular case, we had two sets of commits that did not followed GCA. The vault removal of unused code and mine work on bootstrap and test cases. Going forward we should enforce GCA on all of those. Perhaps even have a github action to validate it.

True marce, we can do the GCA and enforce it. Build team has a point that their build code is different in both versions and they want to avoid the pain of merging their changes to 8.1 (if they do a change on 8.0). It's just blind null merge always for them.

Either they adapt and do null merge or we add an exemption to their dir. We can finalize this later.

**Review by satya-bodapati — APPROVED** [review]

**Comment by altmannmarcelo** [comment]
@satya-bodapati ack, lets take this one offline. I would like to understand the exclude of GCA possibility.

**Pull request merged**
