### PR TITLE
Pxb 8.0 1982

### PR DESCRIPTION
**Pull request by rahulmalik87**
pxb-1338 is null merge.

### CODE REVIEW

**Comment by rahulmalik87** [comment]
./run.sh -t t/history_on_server.sh
Using /home/rahul.malik/MySQL/build/x8/xtrabackup-test/test/var as test root
Detecting server version...
Running against MySQL 8.0.19-debug (InnoDB 8.0.19)
Using 'xtrabackup' as xtrabackup binary
Using 8 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
history_on_server                        w1	[passed]    33
==============================================================================
Spent 33 of 50 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output
{smm-12-d40aec x8 o8 test}$


/run.sh -t t/history_on_server.sh
Using /home/rahul.malik/MySQL/build/x8/xtrabackup-test/test/var as test root
Detecting server version...
Running against Percona Server 8.0.18-9-debug (XtraDB 8.0.18-9)
Using 'xtrabackup' as xtrabackup binary
Using 8 parallel workers

==============================================================================
TEST                                   WORKER    RESULT     TIME(s) or COMMENT
------------------------------------------------------------------------------
history_on_server                        w1	[passed]    33
==============================================================================
Spent 33 of 51 seconds executing testcases

SUMMARY: 1 run, 1 successful, 0 skipped, 0 failed

See results/ for detailed output

**Comment by satya-bodapati** [comment]
@rahulmalik87 Please do manual test which shows locked time in seconds (non-zero). This mtr test means nothing

**Comment by rahulmalik87** [comment]
lock time out with Upstream(with and without --no-lock)

mysql>
mysql> select * from xtrabackup_history\G
*************************** 1. row ***************************
            uuid: 643a6cf1-4bcd-11ea-8477-002590d40aec
            name: NULL
       tool_name: xtrabackup
    tool_command: --target-dir=/home/rahul.malik/MySQL/data/xo8 --core-file --user=root --socket /tmp/socket_1320.sock --keyring-file-data=/home/rahul.malik/MySQL/data/o8/key.key --xtrabackup-plugin-dir=/home/rahul.malik/MySQL/src/x8/bld/plugin_output_directory --history --backup
    tool_version: 8.0.9
ibbackup_version: 8.0.9
  server_version: 8.0.19-debug
      start_time: 2020-02-10 06:20:06
        end_time: 2020-02-10 06:20:11
       lock_time: 2
      binlog_pos: filename 'binlog.000002', position '155'
 innodb_from_lsn: 0
   innodb_to_lsn: 75001400
         partial: N
     incremental: N
          format: file
         compact: N
      compressed: N
       encrypted: N
*************************** 2. row ***************************
            uuid: c2b43fd2-4bcd-11ea-8477-002590d40aec
            name: NULL
       tool_name: xtrabackup
    tool_command: --target-dir=/home/rahul.malik/MySQL/data/xo8 --core-file --user=root --socket /tmp/socket_1320.sock --keyring-file-data=/home/rahul.malik/MySQL/data/o8/key.key --xtrabackup-plugin-dir=/home/rahul.malik/MySQL/src/x8/bld/plugin_output_directory --history --no-lock --backup
    tool_version: 8.0.9
ibbackup_version: 8.0.9
  server_version: 8.0.19-debug
      start_time: 2020-02-10 06:22:44
        end_time: 2020-02-10 06:22:49
       lock_time: 0
      binlog_pos: filename 'binlog.000003', position '967'
 innodb_from_lsn: 0
   innodb_to_lsn: 118261327
         partial: N
     incremental: N
          format: file
         compact: N
      compressed: N
       encrypted: N
2 rows in set (0.01 sec)

mysql>

**Comment by rahulmalik87** [comment]
with percona server with and without --lock-time

mysql> mysql> select * from xtrabackup_history\G
*************************** 1. row ***************************
            uuid: 29f83496-4bce-11ea-bd48-002590d40aec
            name: NULL
       tool_name: xtrabackup
    tool_command: --target-dir=/home/rahul.malik/MySQL/data/xp8 --core-file --user=root --socket /tmp/socket_1220.sock --keyring-file-data=/home/rahul.malik/MySQL/data/p8/key.key --xtrabackup-plugin-dir=/home/rahul.malik/MySQL/src/x8/bld/plugin_output_directory --history --backup
    tool_version: 8.0.9
ibbackup_version: 8.0.9
  server_version: 8.0.18-9-debug
      start_time: 2020-02-10 06:25:37
        end_time: 2020-02-10 06:25:42
       lock_time: 2
      binlog_pos: filename 'binlog.000002', position '1116'
 innodb_from_lsn: 0
   innodb_to_lsn: 57601336
         partial: N
     incremental: N
          format: file
         compact: N
      compressed: N
       encrypted: N
*************************** 2. row ***************************
            uuid: 45feb093-4bce-11ea-bd48-002590d40aec
            name: NULL
       tool_name: xtrabackup
    tool_command: --target-dir=/home/rahul.malik/MySQL/data/xp8 --core-file --user=root --socket /tmp/socket_1220.sock --keyring-file-data=/home/rahul.malik/MySQL/data/p8/key.key --xtrabackup-plugin-dir=/home/rahul.malik/MySQL/src/x8/bld/plugin_output_directory --history --history --no-lock --backup
    tool_version: 8.0.9
ibbackup_version: 8.0.9
  server_version: 8.0.18-9-debug
      start_time: 2020-02-10 06:26:24
        end_time: 2020-02-10 06:26:29
       lock_time: 0
      binlog_pos: filename 'binlog.000003', position '155'
 innodb_from_lsn: 0
   innodb_to_lsn: 84106627
         partial: N
     incremental: N
          format: file
         compact: N
      compressed: N
       encrypted: N
2 rows in set (0.00 sec)

mysql>

**Review by satya-bodapati — APPROVED** [review]
LGTM

**Pull request merged**
