### PR TITLE
PXB-2566 Missing parameter on advanced encryption documentation (8.0)

### PR DESCRIPTION
**Pull request by patrickbirch**
Merged 2.4 version
modified:   source/advanced/encrypted_innodb_tablespace_backups

### CODE REVIEW

**Review by altmannmarcelo — CHANGES_REQUESTED** [review]
The actual issue is a few lines above at https://github.com/percona/percona-xtrabackup/blame/percona-xtrabackup-8.0.26-18/storage/innobase/xtrabackup/doc/source/advanced/encrypted_innodb_tablespace_backups.rst#L392


```
The same passphrase should be specified for the `prepare` command:

.. code-block:: bash
   $ xtrabackup --prepare --target-dir=/data/backup
```

We are saying we should use the same passphrase but we are not adding it to the backup command. Please adjust as below:

From:
```
$ xtrabackup --prepare --target-dir=/data/backup
```
To:
```
$ xtrabackup --prepare --target-dir=/data/backup \
--transition-key=MySecetKey
```

**Comment by altmannmarcelo** [comment]
2.4 is also wrong

**Comment by patrickbirch** [comment]
Fixed.

**Review by altmannmarcelo — APPROVED** [review]
LGTM

**Pull request merged**
