### PR TITLE
Added support for session tokens

### PR DESCRIPTION
**Pull request by mikeamzn**
https://jira.percona.com/browse/PXB-2146

I also tested these changes locally with a real s3 bucket/account.

### CODE REVIEW

**Comment by mikeamzn** [comment]
Can I get a review here?

**Comment by mikeamzn** [comment]
Ping here. Can I get a review please?

**Comment by george-lorch** [comment]
@mikeamzn first, thank you for your contribution.  This is in the work queue.  Our team is extremely busy with other critical tasks at the moment.  It will be reviewed, fixed/altered if needed, merged, and released within our regular release cycle when other work has been completed.  Thanks again for your contribution.

**Comment by mikeamzn** [comment]
Ok, thanks for the update.

**Comment by rahulmalik87** [comment]
merged from 2.4

**Pull request closed without merging**
