### PR TITLE
PXB-2998 : Prepare crashes at dict_load_tables_from_space_id()

### PR DESCRIPTION
**Pull request by satya-bodapati**
https://jira.percona.com/browse/PXB-2998

Problem:
--------
Server on data dicitonary upgrade (ie from DD_VERSION < 8.0.23) to 8.0.23+, upgrades the DD tables using this logic
(Approximate high level view)
1. Create a temporary schema name dd_upgrade_80XX
2. Create modified dd tables in dd_upgrade_80XX schema
3. Do INSERT INTO dd_ugprade_80XX.* FROM mysql.* tables
4. Drop old tables in mysql schema
5. Rename/Update schema of upgraded tables as `mysql` (--> Not done. Server bug)

After the upgrade, these modified DD tables are not moved back to "mysql" schema.

PXB when it finds duplicate SDI (https://jira.percona.com/browse/PXB-2101), handles such IBDs by accessing dictionary table (mysql.tables)

Because of server upgrade bug, dictionary tables schema is left as `dd_upgrade_80XX' in SDI of mysql.ibd.
PXB loads the tables as `dd_upgrade_80XXX.tables' instead of `mysql.tables`. Hence PXB gets nullptr for the DD table mysql.tables.

Fix:
----
All tables in dictionary tablespace mysql.ibd should belong to `mysql` schema. We use mysql schema for all tables in mysql.ibd

### CODE REVIEW

**Comment by rahulmalik87** [comment]
Have you raised the bug on upstream? and how upstream has handled that. given schema name is not mysql?

**Comment by satya-bodapati** [comment]
> Have you raised the bug on upstream? and how upstream has handled that. given schema name is not mysql?

Not yet, I will do and report here @rahulmalik87 
Upstream dictionary loading doesn't look by name. That is because it asks InnoDB to initialize these hardcode tables and it doesn't use the names.

**Comment by satya-bodapati** [comment]
@rahulmalik87 https://bugs.mysql.com/bug.php?id=110194

**Review by altmannmarcelo — CHANGES_REQUESTED** [review]
Changes make sense, I am looking a bit deeper into it, meanwhile can you please submit jenkins?

**Comment by satya-bodapati** [comment]
https://pxb.cd.percona.com/job/percona-xtrabackup-8.0-test-param/286/

**Review by rahulmalik87 — APPROVED** [review]
LGTM

**Review by altmannmarcelo — APPROVED** [review]
LGTM

**Pull request merged**
