### PR TITLE
Jira DOC-546

### PR DESCRIPTION
**Pull request by borys-belinsky**

### CODE REVIEW

**Comment by borys-belinsky** [comment]
Although there are a lot of lines that differ, there is only one essential change: where the pass option is becomes password. Other changes are insignificant: line breaks at 80 columns and removing the unnecessary indentation.

**Review by gl-sergei — CHANGES_REQUESTED** [review]
Please squash commits. The change itself looks good. Have you follow GCA workflow for this branch?

**Comment by borys-belinsky** [comment]
Those ugly commits are the result of my attempt to fix a mistake I made: initially I cloned the repository without first forking it. I have squashed the three commits into one now. Hope it will not cause any trouble

**Comment by gl-sergei** [comment]
Much better now, but there is still an issue that 'jira-doc-546' branch is based on 2.3 HEAD instead of GCA. We have GCA workflow documented [here](https://intranet.percona.com/dokuwiki/dev:mysqldev:submitting_changes) and we follow it for Percona Server and Xtrabackup. Please take a look at this page and rebase your branch on top of the GCA commit. Should you have any issues or if you need help to figure out exact git commands, don't hesitate to ping me on Slack.

**Pull request closed without merging**
